---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/figures_Letterhead Short General_Messages/figures_Letterhead Short
      General_Messages.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/219716/articles/280290/master/file/figures/figures_Letterhead%20Short%20General_Messages/figures_Letterhead%20Short%20General_Messages.csv"
